version: '3.3'

services:
  nginx:
    image: nginx:1.13.11
    restart: always
    volumes:
      - "./etc/nginx/default.vhost.conf:/etc/nginx/conf.d/default.conf"
      - "./src:/var/www/html"
    ports:
      - "8000:80"
    depends_on:
      - php

  php:
    build: ./dockerfiles/php
    restart: always
    volumes:
      - "./src:/var/www/html"
      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/custom.ini"
    environment:
      - "PHP_IDE_CONFIG=serverName=PHPSTORM_DOCKER"
